name: Update
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout
      run: |
        echo 'testing'
